sudo: required
jdk: oraclejdk8
language: android
android: 
 components: 
  - platform-tools
  - tools
  - build-tools-23.0.3
  - android-23
  - extra-android-m2repository
  - extra-android-support
  - sys-img-armeabi-v7a-android-21
env:
 global:
  - ADB_INSTALL_TIMEOUT=8
  - JAVA8_HOME=/usr/lib/jvm/java-8-oracle
before_install: 
 - cd Redgram
before_script:
 - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
 - emulator -avd test -no-skin -no-audio -no-window &
 - android-wait-for-emulator
 - adb shell input keyevent 82 &
script:
 - ./gradlew build connectedCheck
notifications:
 slack: redgram:Pa16hs1sc38HqR8aOBwxU46f
